### ISSUE TITLE
proto 目录的 address.pb.go 是 bazel 生成的吗？

### ISSUE THREAD

**Issue by loyalpartner** [backendcloud/example#10]
请问

https://github.com/backendcloud/example/blob/master/bazel-sample/protobuf/proto/address.pb.go

这个 go 文件是 bazel 生成的吗？

**Comment by backendcloud** [comment]
是的，
https://www.backendcloud.cn/2022/07/27/bazel-protobuf-demo
有详细的说明

**Comment by backendcloud** [comment]
> 请问
> 
> https://github.com/backendcloud/example/blob/master/bazel-sample/protobuf/proto/address.pb.go
> 
> 这个 go 文件是 bazel 生成的吗？

是的，
https://www.backendcloud.cn/2022/07/27/bazel-protobuf-demo
有详细的说明

**Comment by loyalpartner** [comment]
> > 请问
> > https://github.com/backendcloud/example/blob/master/bazel-sample/protobuf/proto/address.pb.go
> > 这个 go 文件是 bazel 生成的吗？
> 
> 是的， https://www.backendcloud.cn/2022/07/27/bazel-protobuf-demo 有详细的说明

这个文章我已经读过了，我把 protobuf/proto/address.pb.go, 然后执行 

```bash
bazel run //bazel-sample/protobuf/proto:proto
```
address.pb.go 并没有直接生成到 bazel-sample/protobuf/proto 目录

**Comment by backendcloud** [comment]
我没这样试过，
可以先试试文章里的步骤
先通过 bazel run //:gazelle 生成BUILD文件
然后通过bazelisk build 生成 *.pb.go 文件
